E_SUCCESS = "E_SUCCESS"
E_INTERNAL_ERROR = "E_INTERNAL_ERROR"

E_CONFIG_INVALID = "E_CONFIG_INVALID"
E_FUZZER_ABORTED = "E_FUZZER_ABORTED"
E_FUZZER_LAUNCH_ERROR = "E_FUZZER_LAUNCH_ERROR"

E_RAM_LIMIT_EXCEEDED = "E_RAM_LIMIT_EXCEEDED"
E_TMPFS_LIMIT_EXCEEDED = "E_TMPFS_LIMIT_EXCEEDED"